spring.application.name=primera-wed
# Puerto del servidor
server.port=8080

# Configuración H2
spring.datasource.url=jdbc:h2:mem:tiendadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=update

# Deshabilitar caché de Thymeleaf para ver cambios HTML en tiempo real
spring.thymeleaf.cache=false